language: go
sudo: false
go:
  - 1.13.x

env:
  - GO111MODULE=on

cache:
  directories:
    - $GOPATH/pkg/mod

notifications:
  email: false

install:
  - chmod +x ${TRAVIS_BUILD_DIR}/build/validate.sh
  - go get github.com/captncraig/setStatus
  - npm i -g typescript@2.4.2

script: $GOPATH/src/bosun.org/build/validate.sh
